# Generated by Django 3.2.6 on 2021-08-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_allproduct_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='instock',
            field=models.BooleanField(default=True),
        ),
    ]
