# Generated by Django 3.2.6 on 2021-09-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='defaultprofile.png', null=True, upload_to='photoprofile'),
        ),
    ]
