# Generated by Django 3.2.6 on 2021-10-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_cart_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cartquan',
            field=models.IntegerField(default=0),
        ),
    ]
